- definitions/windows.yaml
> Add WMIPhysicalMemory, fix alphabetic ordering

- definitions/windows.yaml
Added multiple Windows artifacts for review.  Some of these may need to be broken up or documented differently, but they have all been tested and should work correctly.
> Added more Windows artifacts

- definitions/linux.yaml
Add artifacts needed to process (non-systemd style) debian init scripts.
> Add lsb-style runlevel artifacts.

- artifacts/source_type_test.py
> Fix minor lint issues.

- definitions/unix_common.yaml
@joachimmetz @pidydx 
GRR has a parser that works on /etc/passwd, so I need these split out.
> Split unix passwd, shadow, group artifacts.

- definitions/unix_common.yaml
- definitions/windows_bootstrap.yaml
This is not exactly ideal, but is less bad than the current state, which is broken.
> Fix SystemDrive.

- definitions/unix_common.yaml
> Fix style issues.

- definitions/linux.yaml
Let's collect xinetd service definitions as well.
> Add xinetd configuration artifacts.

- .gitignore
- .travis.yml
- artifacts/registry.py
- artifacts/registry_test.py
- tools/validator.py
- tox.ini
- Python 3 support
- [Tox](https://tox.readthedocs.org/en/latest/)  support
> Python 3 support

- docs/Artifacts definition format and style guide.asciidoc
Example used the wrong attribute.
> Correction from artifact_list to names in example

- utils/pylintrc
- utils/run_linter.sh
@destijl for review
basically copied what we use for plaso and dfvfs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/53)
> Added pylintrc and helper script.

- definitions/linux.yaml
Added stating of parent folders already defined in existing artifiacts and also added collecting information about /etc/cron.allow, /etc/cron.deny, /etc/at.allow and /etc/at.deny.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/52)
> Added more cron defintions

- README.md
- artifacts/registry_test.py
- config/dpkg/control
- definitions/windows.yaml
- docs/Artifacts definition format and style guide.asciidoc
Removed unnecessary white spaces and changed double quotes to single quotes for consistency.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/54)
> Minor Style improvments

- definitions/windows.yaml
@joachimmetz
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/55)
> Add Windows Update auto update status reg keys.

- definitions/linux.yaml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/57)
> Adding APT & Yum sources artifacts

- definitions/windows.yaml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/56)
> Add WinRAR AV and Viewer keys

- definitions/linux.yaml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/58)
> Add LinuxFstab to fetch mount options in /etc/fstab.

- artifacts/source_type.py
- artifacts/source_type_test.py
- definitions/windows.yaml
@joachimmetz
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/59)
> Fix WinRAR artifacts, add better validation.

- definitions/linux.yaml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/60)
> Add rsyslog definition.

- definitions/linux.yaml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/61)
> Add SysVInit artifact, and aggregate LinuxServices artifact.

- definitions/linux.yaml
- definitions/unix_common.yaml
Creating one artifacts to access common shell configurations and history files for both system users and root.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/63)
> Combine Users & Root artifacts into one

- definitions/windows.yaml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/66)
> Style: Remove whitespaces from end of line

- definitions/linux.yaml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/68)
> Get files underneath rsyslog.d

- definitions/linux.yaml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/69)
> Add ntp configuration file.

- definitions/linux.yaml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/70)
> Adding syslog-ng configuration artifact

- definitions/linux.yaml
- definitions/linux_proc.yaml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/74)
> Add collection of sysctl state via command output.

- tests/__init__.py
- tests/reader_test.py
- tests/source_type_test.py
- tests/validator_test.py
@joachimmetz
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/77)
> Minor lint fixes

- definitions/linux.yaml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/79)
> Add pam file and ps command artifacts.

- definitions/windows.yaml
Fixes https://github.com/ForensicArtifacts/artifacts/issues/78
by removing an identical duplicate.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/81)
> Remove WindowsLoadAndRunValues dup.

- definitions/webbrowser.yaml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/80)
> Artifact for Chrome Extension registry keys.

- definitions/linux.yaml
@joachimmetz FYI, I took this out temporarily, and am putting it back in.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/83)
> Re-instated linuxsysv in linux services.

- definitions/windows.yaml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/85)
> Add BITS queue manager DBs.

- definitions/windows.yaml
@destijl for review
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/91)
> Added AppCompatCache and ProgramsCache definitions

- definitions/webbrowser.yaml
> Added web browser meta artifacts.

- definitions/antivirus.yaml
@destijl small changes for MS AV
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/93)
> Additional path for Microsoft Anti-Virus Quarantine files.

- tools/validator.py
@destijl for review
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/90)
> Fix for Python 3 compatibility #88

- definitions/webbrowser.yaml
- definitions/windows.yaml
These are mostly for older versions, but some less common malware persistence locations.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/95)
> Adding additional persistence locations targeted by malware.

- docs/Artifacts definition format and style guide.asciidoc
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/96)
> Changes to work around broken manual placed TOC rendering.

- definitions/darwin.yaml
Add an artifact that runs `hdiutil info` and collects its output.
This commit depends on a client template change that's on its way
to be synced into github.com/google/grr at the time of this writing.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/98)
> OSX - Provide a flow collecting mounted DMG files info.

- artifacts/definitions.py
- definitions/cloud_services.yaml
- docs/Artifacts definition format and style guide.asciidoc
@destijl for review
Note that I'll need to create the forensics wiki page and add Mac OS X at a later date
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/92)
> Added Windows Google Drive client artifacts.

- definitions/windows.yaml
Mostly related to different persistence techniques.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/86)
> Add several more Windows artifacts.

- definitions/windows.yaml
This broke GRR Interrogate.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/101)
> Fixed syntax for GRR usage

- artifacts/source_type.py
- Include base_object
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/100)
> Fix WMIQuerySourceType validation.

- definitions/windows.yaml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/102)
> Add WMIEnumerateASEC and WMIEnumerateCLEC.

- definitions/windows.yaml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/103)
> Fix alphabetical ordering.

- definitions/antivirus.yaml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/104)
> Added Symantec log and quarantine files

- definitions/windows.yaml
> update RunGrpConv keys to be a list

- definitions/windows.yaml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/108)
> Windows Most recent app registry key

- definitions/windows.yaml
WindowsShellExecuteHooks
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/111)
> Added WindowsShellExecuteHooks artifact

- definitions/windows.yaml
WindowsWinlogonSystem
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/110)
> Added WindowsWinlogonSystem artifact

- definitions/windows.yaml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/109)
> Windows policy disallow run

- definitions/webbrowser.yaml
- definitions/windows.yaml
InternetExplorerBrowserHelperObjects
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/112)
> add InternetExplorerBrowserHelperObjects

- definitions/windows.yaml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/114)
> add WindowsShellIconOverlayIdentifiers

- definitions/windows.yaml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/115)
> Added a bunch more windows reg persistence keys

- definitions/linux.yaml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/117)
> Add apt keyring trust stores.

- definitions/linux.yaml
@parkisan this is just a alphabetic re-order
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/121)
> Fix alphabetical order in linux.yaml

- artifacts/definitions.py
- definitions/darwin.yaml
> removed trailing whitespace

- definitions/webbrowser.yaml
- definitions/windows.yaml
@destijl largely clean up and created a meta artifact for persistence Registry keys.
Also documentation (work in progress) can be found here: http://forensicswiki.org/wiki/Windows_Registry#Persistence_keys
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/116)
> Changes for Windows persistence keys.

- definitions/darwin.yaml
@liamjm
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/124)
> Add missing provides to OSXUsers.

- definitions/windows.yaml
@liamjm
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/125)
> Remove trailing whitespace

- definitions/linux.yaml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/119)
> AllUserShellHistory was collecting configs, not shell history.

- definitions/linux.yaml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/129)
> Add artifact for PCI Devices

- definitions/windows.yaml
Existing artifact: WindowsCommandProcessorAutoRun
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/131)
> remove duplicate for CmdExeAutoRun

- definitions/windows.yaml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/130)
> add more artifacts to WindowsPersistenceRegistryKeys

- definitions/windows.yaml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/132)
> added AppKey windows persistence

- definitions/windows.yaml
@joachimmetz
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/136)
> Fix ServiceControlManagerExtension name

- definitions/windows.yaml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/133)
> Explorer Context Menu Handlers

- artifacts/errors.py
- definitions/windows.yaml
- tests/validator_test.py
- tools/validator.py
Also fix existing errors.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/138)
> Add validation for meta artifact dependencies.

- definitions/installed_modules.yaml
- definitions/modules.yaml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/118)
> Add python and ruby modules.

- tools/stats.py
@jbmetz. The result is on the front page already so you can see what it looks like as rendered Markdown.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/140)
> Add tool to print stats about artifact files.

- artifacts/artifact.py
- artifacts/reader.py
- artifacts/registry.py
- artifacts/source_type.py
- setup.py
- tests/validator_test.py
- tools/validator.py
Changes for: https://github.com/ForensicArtifacts/artifacts/issues/135
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/142)
> Removed explicit format type indicators #135

- artifacts/definitions.py
- definitions/linux.yaml
- definitions/unix_common.yaml
Changes for issue: https://github.com/ForensicArtifacts/artifacts/issues/123
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/144)
> Added History Files category #123

- definitions/windows.yaml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/147)
> Added Windows temporary directory definition

- artifacts/artifact.py
- artifacts/definitions.py
- artifacts/source_type.py
- definitions/cloud_services.yaml
- definitions/installed_modules.yaml
- definitions/kaspersky_careto.yaml
- definitions/linux.yaml
- definitions/linux_proc.yaml
- definitions/unix_common.yaml
- definitions/webbrowser.yaml
- definitions/windows.yaml
- docs/Artifacts definition format and style guide.asciidoc
- test_data/definitions.yaml
- tests/reader_test.py
- tests/source_type_test.py
- tools/validator.py
Changes for: https://github.com/ForensicArtifacts/artifacts/issues/139
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/143)
> Renamed ARTIFACT to ARTIFACT_GROUP #139

- definitions/windows.yaml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/148)
> Changed WindowsNetshHelpers to WindowsNetworkShellHelpers

- definitions/windows.yaml
- setup.py
- tests/validator_test.py
- tools/stats.py
- tools/validator.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/145)
> Added check for duplicate Registry key paths #41

- definitions/linux.yaml
Add an artifact to collect SSH host keys from /etc/ssh/ssh_host_*_key.pub.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/127)
> Add SSH Host Key artifact

- definitions/cloud_services.yaml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/153)
> Added SkyDrive client artifact.

- definitions/windows_bootstrap.yaml
- tests/reader_test.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/151)
> Changed assertEqual with None into assertIsNone.

- definitions/webbrowser.yaml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/149)
> Added Firefox cache artifact.

- definitions/windows.yaml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/141)
> Added Windows COM Registry keys.

- definitions/windows.yaml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/137)
> lots of namespace reg paths

- config/dpkg/control
- config/dpkg/rules
- setup.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/155)
> Changes for deployment of rpm and dpkg.

- setup.cfg
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/157)
> Fix for bdist_rpm

- definitions/linux.yaml
@joachimmetz
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/159)
> Add iptables rule list command.

- definitions/linux.yaml
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/158)
> Changed initrd and added grub config definitions.

- definitions/webbrowser.yaml
Add Chrome preferences file artifact to webbrowser.yaml
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/161)
> add Chrome preferences file artifact

- definitions/linux.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/164)
> Add artifacts for linux syslogs and linux timezone file.

- definitions/linux.yaml
Add the following Linux log artifacts:
- /var/log/messages*
- /var/log/kern.log*
- /var/log/dpkg.log*
- /var/log/apt/history.log*
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/165)
> Add Linux log artifacts

- definitions/applications.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/163)
> Added NPM cache artifact.

- definitions/windows.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/166)
> Add Windows WMILastBootUpTime

- artifacts/artifact.py
- tests/reader_test.py
- tests/registry_test.py
@joachimmetz
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/160)
> Detect and handle bad keys in yaml definition.

- definitions/windows.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/167)
> Added Windows Amcache.hve artifact.

- definitions/antivirus.yaml
- definitions/config_files.yaml
- definitions/installed_modules.yaml
- definitions/kaspersky_careto.yaml
- definitions/linux.yaml
- definitions/linux_bootstrap.yaml
- definitions/linux_proc.yaml
- definitions/unix_common.yaml
- definitions/windows.yaml
- definitions/windows_bootstrap.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/168)
> Add Linux DSDTTable

- definitions/windows.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/176)
> Added RecentFileCache.bcf definition.

- definitions/legacy.yaml
- tools/validator.py
Add back in some artifacts that were removed in:
https://github.com/ForensicArtifacts/artifacts/pull/152
but are required for GRR interrogate to work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/184)
> Add GRR legacy names.

- definitions/legacy.yaml
- tools/validator.py
Also exempt legacy.yaml from duplicate checking.
Apply yapf python formatter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/185)
> Add missing GRR legacy names

- config/dpkg/changelog
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/190)
> Fixes for dpkg files.

- artifacts/reader.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/192)
> Clean up of artifact reader after changes.

- definitions/windows.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/193)
> Added Windows Metro artifacts.

- definitions/windows.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/195)
> Added Windows installation date and time artifact.

- definitions/applications.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/196)
> Added Office MRU artifact definition.

- definitions/config_files.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/200)
> Add user ssh config to config_files artifacts.

- definitions/linux.yaml
- definitions/unix_common.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/201)
> Make common shell configs/histories Darwin-compatible.

- definitions/wmi.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/205)
> Adding a WMIVolumeShadowCopies artifact.

- definitions/windows.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/206)
> Add OpenSaveMRU artifacts

- definitions/cloud_services.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/207)
> Add Mac GoogleDriveClient definition.

- .style.yapf
- MANIFEST.in
- appveyor.yml
- config/dpkg/control
- dependencies.ini
- requirements.txt
- run_tests.py
- setup.cfg
- utils/dependencies.py
- utils/update_dependencies.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/209)
> Added dependency utility scripts

- definitions/windows.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/197)
> Added registered type libraries definition.

- .travis.yml
- README.md
- appveyor.yml
- artifacts/__init__.py
- artifacts/artifact.py
- artifacts/definitions.py
- artifacts/reader.py
- artifacts/registry.py
- artifacts/source_type.py
- artifacts/writer.py
- config/travis/install.sh
- requirements.txt
- tests/reader_test.py
- tests/registry_test.py
- tests/source_type_test.py
- tests/style_test.py
- tests/test_lib.py
- tests/validator_test.py
- tests/writer_test.py
- tools/stats.py
- utils/update_dependencies.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/211)
> Added MacOS and coveralls support to tests

- definitions/linux.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/214)
> Added Linux hostname and passwd artifact definitions

- artifacts/artifact.py
- artifacts/registry.py
- tests/registry_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/213)
> Added means to register custom artifact types #175

- artifacts/__init__.py
- definitions/macos.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/215)
> Added macOS plist file artifact definitions

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/220)
> YouTube account has been removed, video no longer available.

- data/windows.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/221)
> Added Windows version artifact definition

- data/legacy.yaml
- data/windows.yaml
- tools/validator.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/222)
> Changes to validator #216 and replaced %%current_control_set%% #120

- data/windows.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/223)
> Corrected WindowsEnvironmentVariableAllUsersProfile definition

- data/linux_proc.yaml
Gathers /proc/net/arp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/224)
> Adding LinuxProcArp to linux_proc.yaml

- artifacts/artifact.py
- artifacts/definitions.py
- artifacts/errors.py
- artifacts/reader.py
- artifacts/registry.py
- artifacts/source_type.py
- artifacts/writer.py
- setup.py
- tools/stats.py
- tools/validator.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/225)
> Updated code style

- data/windows.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/226)
> Add Windows DNS and DHCP server artifact definition

- data/linux.yaml
- data/macos.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/227)
> Added LinuxLocalTime artifact definition

- artifacts/__init__.py
- config/dpkg/changelog
- data/linux.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/230)
> Added LinuxSystemdOSRelease and updated LinuxRelease definitions

- artifacts/__init__.py
- config/dpkg/changelog
- data/legacy.yaml
- data/linux.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/234)
> Split LSB and non-LSB release artifact definitions

- artifacts/__init__.py
- config/dpkg/changelog
- utils/update_version.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/237)
> Fixed version update of config/dpkg/changelog #236

- data/wmi.yaml
Returns all information about the registered AV product.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/239)
> Adding WMIAntivirusProduct to wmi.yaml

- data/config_files.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/241)
> added darwin os to /etc/ssh/sshd_config file artifact

- data/windows.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/242)
> Add Sysmon event log artifact definition

- data/linux.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/245)
> Updated LinuxLSBRelease

- data/linux.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/244)
> Added LinuxIssueFile

- data/windows.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/251)
> Removing a provides directive that uses a deprecated name.

- README
- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/249)
> Updated README

- data/windows.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/250)
> Added WindowsSystemResourceUsageMonitorDatabaseFile definition

- data/windows.yaml
Add artifact definition for primary files and transaction log files from RegBack Registry backup folder.
> Added Windows system registry backup files artifact

- data/windows.yaml
This file is available since Windows 10 and version 1803 (April 2018).
FTR - The file is a SQLite database and a tool for parsing (besides looking into it with e.g. SQLite browser manually) is available here: https://binaryforay.blogspot.ch/2018/05/introducing-wxtcmd.html.
> Add Windows activities cache artifact definition

- data/macos.yaml
See also: https://www.crowdstrike.com/blog/i-know-what-you-did-last-month-a-new-artifact-of-execution-on-macos-10-13/
> Added CoreAnalytics log files to macOS artifacts.

- data/webbrowser.yaml
Added Linux path in ChromeCache artifact definition
> Added Linux path in ChromeCache artifact definition

- data/windows.yaml
Add aritfact for listing the Windows Firewall rules.
> Added WindowsFirewallLogFile and WindowFirewallRules artifact definitions

- data/windows.yaml
Add additional Windows Firewall artifact for just the enabled Windows Firewall rules
> Add WindowsFirewallEnabledRules

- data/windows.yaml
How about these two artifacts to help determine Windows kernel versions?
> Added Windows ReleaseID and UBR registry keys

- data/ntfs.yaml
Added $LogFile as an artifact specific to NTFS.
> ntfs.yaml updates

- .travis.yml
- artifacts.ini
- config/travis/install.sh
- config/travis/runtests.sh
Applied updates and added Fedora Core CI tests
> Applied updates and added Fedora Core CI tests

- .travis.yml
- artifacts/reader.py
- config/travis/install.sh
- config/travis/runtests.sh
- setup.py
Migrated tox tests to Bionic on Docker
> Migrated tox tests to Bionic on Docker

- data/instant_messaging.yaml
At the moment it contains only the Skype artifacts moved from macos.yaml file.
Goal is to collect here all Instant Messaging related artifacts from the different platforms.
> Initial commit to collect Instant Messaging applications artifacts

- data/ntfs.yaml
> Change NTFSLogFile urls to list

- artifacts/__init__.py
- config/dpkg/changelog
- config/travis/install.sh
- setup.py
- test_requirements.txt
- tox.ini
Applied updates and changes to setup.py for bdist_rpm
> Applied updates and changes to setup.py for bdist_rpm

- tools/validator.py
Validate environment and users variables in Registry key paths
> Validate environment and users variables in Registry key paths

- tools/validator.py
Validate environment and users variables in Windows paths #311
> Validate environment and users variables in Windows paths #311

- appveyor.yml
- config/travis/install.sh
- config/travis/runtests.sh
- setup.py
- utils/dependencies.py
Changed AppVeyor test to use Python 3.7
> Changed AppVeyor test to use Python 3.7

- data/antivirus.yaml
- tools/validator.py
Changed validator to check globstars in paths
> Changed validator to check globstars in paths

- data/windows.yaml
Add WindowsApplicationShimFiles
Add WindowsApplicationShimRegistryKeys
Add WindowsCOMProperties
Add WindowsBootConfigurationSettings
Add WindowsUpdateSettings
Update WindowsExplorerSettings
Update WindowsSystemRestoreSettings
Update WindowsUserAccountControlSettings
> Add/Update multiple Windows artifact definitions

- .travis.yml
- artifacts/__init__.py
- config/dpkg/changelog
- config/dpkg/rules
- config/travis/runtests.sh
- utils/dependencies.py
Applied updates and added Python 3.8 CI tests
> Applied updates and added Python 3.8 CI tests

- data/webbrowser.yaml
Add Safari cache WAL
Write-Ahead Logging file added
Safari cache case fixed
Add SafariExtensions
> Update Safari cache and add Safari Extensions to webbrowser.yaml

- data/windows.yaml
Added Amcache transaction logs (Log1 and Log2)
> Changed WindowsAMCacheHveFile to include transaction logs

- data/linux.yaml
Added secure log to LinuxAuthLogs section.
Added CentOS and SuSE OS release files to LinuxDistributionRelease section.
Added a section for sudo replay log files, called LinuxSudoReplayLogs.
> Update linux.yaml artifact file

- data/webbrowser.yaml
Adds ChromeCookies, ChromeLocalStorage, ChromeSessionStorage, ChromeFileSystem, and ChromeIndexedDB artifacts, with the latter four also comprising a new ChromeStorage artifact group.
> Chrome storage artifacts

- .travis.yml
- artifacts/__init__.py
- config/dpkg/changelog
- config/travis/runtests.sh
> Updated version

- data/antivirus.yaml
Examples:
- C:/Users/All Users/Microsoft/Windows Defender/Support/MPLog-20210510-062819.log
- C:/Users/All Users/Microsoft/Windows Defender/Support/MPDetection-20210503-154850.log
> MsDefender logs on disk to antivirus.yaml

- artifacts/definitions.py
- data/containerd.yaml
This pull request contains the artifacts related to containerd configuration and log files related to containerd.
> Containerd artifacts

- data/kubernetes.yaml
- data/linux.yaml
- data/macos.yaml
- docs/sources/Format-specification.md
Did a codespell run over the whole code and found various typos
> Codespell check

- data/wmi.yaml
I've created an entry in the Forensics Wiki and linked it up in the artifact definition.
> Added a URL to CCM_RecentlyUsedApps

- data/cloud_services.yaml
Add database file procesed by plaso parser (ref: https://github.com/log2timeline/plaso/pull/4052)
> Update Dropbox definition to include sync_history.db

- data/shell.yaml
Add definitions for fish shell artifacts.
> Add fish shell artifacts.

- data/hadoop.yaml
Will catch recently observed attacks
> Update Hadoop log artifacts

- data/windows.yaml
Added new Windows artifact definitions:
- Windows `Background Activity Moderator (BAM)` and `Desktop Activity Moderator (DAM)` registry keys [program executions]
- `WordWheelQuery` registry key for keywords searched from the Windows start menu [program executions / files and folders access]
- `Map Network Drive MRU` registry key
> Added Windows artifact definitions

- data/linux.yaml
Adding less utility history file
> Added new Linux artifacts

- data/linux.yaml
- Changed LinuxAuthLogs for Red Hat/CentOS
> Fixed LinuxAuthLogs for Red Hat/CentOS

- data/instant_messaging.yaml
- data/macos.yaml
- data/user.yaml
Updating URLs for forensic wiki Fixes #549
> Updated Forensics Wiki URLs

- data/macos.yaml
Fixing a mistake introduced in #550.
> Fixing reference url

- data/unix_common.yaml
Added CUPS job cache file definition.
> Added CupsJobCacheFile definition

- data/webbrowser.yaml
Adds a definition for the Google Platform Notifications leveldb
> Add Google Chrome Platform Notifications

- artifacts/data/applications.yaml
- artifacts/data/file_systems.yaml
- artifacts/data/hadoop.yaml
- artifacts/data/instant_messaging.yaml
- artifacts/data/kubernetes.yaml
- artifacts/data/macos.yaml
- artifacts/data/user.yaml
- artifacts/data/webbrowser.yaml
- artifacts/data/webservers.yaml
- artifacts/data/windows.yaml
- artifacts/data/wmi.yaml
- tests/validator_test.py
- tools/validator.py
Note that the warning does not affect the validation results, mostly cosmetic at this point.
> Changes to validator to warn about sort order

- artifacts/data/macos.yaml
Hi! These are a few new or old locations of artifacts related to startup/login persistence on Mac OS. I plan to contribute some plaso parsers that cover a few of these.
> Add MacOS startup and login artifacts

- artifacts/data/webbrowser.yaml
Include paths to Chrome Beta in webbrowser.yaml
> Include Chrome Beta in web browsers

- artifacts/data/config_files.yaml
Added more Jupyter configuration file paths using the below source.
https://docs.jupyter.org/en/latest/use/jupyter-directories.html#configuration-files
> Add more Jupyter notebook configuration file paths.
