definitions/linux.yaml

Include files inside the directories of cron.* Also /var/spool/cron contains further directories.
LinuxScheduleFiles combines all three scheduling artificats into one.

Update AnacronFiles & LinuxCronTabs and add LinuxScheduleFiles

---

definitions/linux.yaml
definitions/linux_proc.yaml

Move LinuxProcMounts out of the LinuxProcSysHardeningSettings
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/64)

Collect /proc/mounts and /etc/fstab artifacts together.

---

definitions/windows.yaml

This breaks GRR unit tests
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/65)

Typo in WindowsGroupPolicyScripts

---

definitions/linux.yaml

Not covered in the man page but seems to be utilised on at least Debian/Ubuntu by using a @include "/etc/syslog-ng/conf.d/*.conf" at the end of the primary syslog-ng.conf file.
Sorry for the unnecessary overhead :(
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/71)

Multiple configs for syslog-ng

---

definitions/webbrowser.yaml
definitions/windows_bootstrap.yaml

AFAICT local settings is not actually a configurable environment variable, and
is always:
%USERPROFILE%\Local Settings
on the versions of windows where it existed. We never actually populated this
variable in GRR, so I'm going to remove it there as well. This Feeds Cache IE
history location appears to be only for very old versions of windows/IE and
isn't actually listed in the forensicswiki reference.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/75)

Remove users.local_settings

---

definitions/linux.yaml

- Having some parsing issues with this group of artifacts, dropping sysvinit out
temporarily.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/82)

Temporarily remove sysvinit from LinuxServices.

---

definitions/linux.yaml

Oracle Enterprise Linux stores it's rc[0-9].d directories under /etc/rc.d rather than /etc.
e.g. From an OEL system.
-rwxr-xr-x 1 root root 4.3K Jan 19  2011 /etc/rc.d/init.d/ntpd
lrwxrwxrwx 1 root root   14 Jul 29  2013 /etc/rc.d/rc0.d/K74ntpd -> ../init.d/ntpd
lrwxrwxrwx 1 root root   14 Jul 29  2013 /etc/rc.d/rc1.d/K74ntpd -> ../init.d/ntpd
lrwxrwxrwx 1 root root   14 Jul 29  2013 /etc/rc.d/rc2.d/S58ntpd -> ../init.d/ntpd
lrwxrwxrwx 1 root root   14 Jul 29  2013 /etc/rc.d/rc3.d/S58ntpd -> ../init.d/ntpd
lrwxrwxrwx 1 root root   14 Jul 29  2013 /etc/rc.d/rc4.d/S58ntpd -> ../init.d/ntpd
lrwxrwxrwx 1 root root   14 Jul 29  2013 /etc/rc.d/rc5.d/S58ntpd -> ../init.d/ntpd
lrwxrwxrwx 1 root root   14 Jul 29  2013 /etc/rc.d/rc6.d/K74ntpd -> ../init.d/ntpd
[<img …

Add additional paths to LinuxSysVInit for OEL

---

artifacts/definitions.py
artifacts/reader.py
tests/reader_test.py

This catches the sources syntax error we saw in
https://github.com/ForensicArtifacts/artifacts/pull/101.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/105)

Add extra validation.

---

artifacts/artifact.py
artifacts/definitions.py
artifacts/source_type.py
definitions/darwin.yaml

I did the run_test and removed couple of duplicates, however it still fails due to the new labels I have introduced for macro categories: Mail, Cloud, Account.
Artifacts from mac4n6 refer only to FILE type and do not have/include any command or other types so far.
Looking forward to your feedback.
Pasquale
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/87)

Darwin artifacts from mac4n6 project

---

artifacts/source_type.py
definitions/kaspersky_careto.yaml
definitions/windows.yaml
tests/registry_test.py
tests/source_type_test.py

Add some extra checks to the reading of windows Registry Keys
* ensure keys is a list for TYPE_INDICATOR_WINDOWS_REGISTRY_KEY
* for each key, ensure it starts with an acceptable prefix (don't us HKLM for example)
Follow-on tweaks to some of the definitions to pass the new verification.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/113)

Add validation to Win Registry Key prefixes

---

definitions/linux.yaml

Could be useful to check if a DNS has been changed to one controlled by an attacker.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/156)

/etc/resolv.conf added to linux artifacts

---

tools/stats.py

This fixes the following error with python 3:
```
As of 2016-10-23 the repository contains:
| **File paths covered** | **709** |
| :------------------ | ------: |
| **Registry keys covered** | **429** |
| **Total artifacts** | **415** |
**Artifacts by type**
Traceback (most recent call last):
File "/usr/local/bin/stats.py", line 106, in <module>
main()
File "/usr/local/bin/stats.py", line 102, in main
statsbuilder.PrintStats()
File "/usr/local/bin/stats.py", line 95, in PrintStats
self.PrintSourceTypeTable()
File "/usr/local/bin/stats.py", line 44, in PrintSourceTypeTable
self._PrintDictAsTable(self.source_type_counts)
File "/usr/local/bin/stats.py", line 17, in _PrintDictAsTable
key_list.sort()
AttributeError: 'dict_keys' object has no attribute 'sort'
```
---
This change is [<img …

Make stats.py work with python 3

---

definitions/webbrowser.yaml

I assume this has also changed on Windows, but I don't have a Windows Safari install around to test at the moment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/204)

Add Safari SQLite history file.

---

tools/stats.py

I was getting this error:
```
Traceback (most recent call last):
File "/usr/local/bin/stats.py", line 129, in <module>
main()
File "/usr/local/bin/stats.py", line 125, in main
statsbuilder.PrintStats()
File "/usr/local/bin/stats.py", line 116, in PrintStats
self.PrintSummaryTable()
File "/usr/local/bin/stats.py", line 78, in PrintSummaryTable
self.total_count))
ValueError: Unknown format code 's' for object of type 'int'
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forensicartifacts/artifacts/228)

Fix stats.py format code

---

artifacts/reader.py
artifacts/source_type.py

Currently some regression tests fail with python 3.6.2:
```
======================================================================
ERROR: testBadKey (reader_test.YamlArtifactsReaderTest)
Tests if top level keys are correct.
----------------------------------------------------------------------
Traceback (most recent call last):
File "/wrkdirs/usr/ports/security/py-artifacts/work/artifacts-20170909/tests/reader_test.py", line 166, in testBadKey
_ = list(artifact_reader.ReadFileObject(file_object))
File "./artifacts/reader.py", line 347, in ReadFileObject
artifact_definition = self.ReadArtifactDefinitionValues(yaml_definition)
File "./artifacts/reader.py", line 207, in ReadArtifactDefinitionValues
raise errors.FormatError('Undefined keys: {0:s}'.format(different_keys))
TypeError: …
```

Fix some regression tests with python 3.6.2

---

data/windows.yaml

When using the variable `%%users.appdata%%`, which is provided in the registry artifact `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders`, the `Roaming` part is already included. This is consistent with other usages, for example with `users.localappdata`.

Fix usage of %%users.appdata%%

---

data/windows.yaml

Added proxy pac into the name so it's easier to find it (e.g. inside GRR). AutoConfigURL is seldom used when searching for that key.

Add proxy pac "AutoConfigURL" registry artifact

---

data/linux.yaml

The current definition points to /var/log/messages.log*, but the files are actually named /var/log/messages* (without .log)

Bug fix for LinuxMessagesLogFiles definition

---

data/macos.yaml

From the blog post https://www.swiftforensics.com/2018/05/bash-sessions-in-macos.html:
> While all versions of macOS have provided bash_history for users, since macOS 10.11 (El Capitan), we get even more information on terminal history through the bash sessions files. This is not a replacement for the old .bash_history file which is still there.
>
> The location you want to go to is  /Users/\<USER\>/.bash_sessions/*
>
> TERM_SESSION_ID.history    --> Contains session history
TERM_SESSION_ID.historynew --> Mostly blank/empty
TERM_SESSION_ID.session    --> Contains the last session resume date and time

Add MacOS bash session artifact

---

artifacts/definitions.py
data/antivirus.yaml
data/cloud_services.yaml
data/java.yaml
tools/validator.py

Added check to validate Windows path separator #265

Added check to validate Windows path separator #265

---

data/docker.yaml

The previous "DockerContainerLogs" artifact is actually specific to Docker installations on a GKE environment.
I'm also adding docker (storage v1 & V2) container configuration files

Rename GKE specific artifact and add Docker config

---

data/macos.yaml

Added several new artifacts and corrected the path of the one related to Apple Mail application (new versions can have the path different from "V2", but still always V followed by one digit --> "V[0-9]")

Several macOS new artifacts

---

artifacts/definitions.py

I think it would be beneficial to add three new labels for defining artifacts:
- DB and Plist are very useful in a macos (and mobile eventually) environment, where almost all data and configuration are stored in either format. 
- Persistence would be interesting so that we can mark known locations/artifacts of malware persistence mechanisms as such.

Added artifact labels for plist and SQLite

---

tests/reader_test.py
tests/registry_test.py
tests/test_lib.py
tests/writer_test.py

skipUnlessHasTestFile decorator conflicts with some build systems replacing by a runtime solution.

Replaced skipUnlessHasTestFile decorator with unittest.SkipTest

---

data/windows.yaml

Changed definition of WindowsUninstallKeys #329

Changed definition of WindowsUninstallKeys #329

---

data/windows.yaml

One of the registry keys related to the Logon Script environment persistence mechanism incorrectly listed 'UserMprLogonScript' as the environment variable name when it should be 'UserInitMprLogonScript' (per http://www.hexacorn.com/blog/2014/11/14/beyond-good-ol-run-key-part-18/).
Also, two of the registry keys had the invisible soft hyphen character inserted.  I'm not sure if this affects things when these data files are used, but it's probably best to remove them. `git diff` from the console shows these changes better than the GitHub UI:
```diff
-      - '%%environ_systemroot%%\system32\Windows<U+00AD>PowerShell\v1.0\profile.ps1'
-      - '%%environ_systemroot%%\system32\Windows<U+00AD>PowerShell\v1.0\Microsoft.PowerShell_profile.ps1'
+      - …
```

[WIP] Fix several existing artifacts, add in new ones

---

ACKNOWLEDGEMENTS
data/antivirus.yaml
data/windows.yaml

Updates from 89b0081: 
- Add WindowsDefenderExclusionList
- Add WindowsFontDrivers
- Add WindowsWinlogonGPExtensions
- Add WindowsSearchFilterHandlers
- Add WindowsSessionManagerS0InitialCommand
- Add WindowsSetupCommandLine
- Modify WindowsFileTypeAutorunAssociations
- Modify WindowsMultiMediaDrivers
Updates from de93e52:
- Add WindowsActionCenterSettings
- Add WindowsFirewallAuthorizedApplications
- Add WindowsFirewallPolicySettings
- Add WindowsPendingGPOs
- Add WindowsSecurityCenterSettings
- Add WindowsSystemRestoreSettings
- Add WindowsUserAccountControlSettings
- Add WindowsUpgradeSettings
- Modify WindowsServices
- Modify WindowsStubPaths
Updates from c7139e2
- Add WindowsProxyServerSettings
- Add WindowsDisallowedSystemCertificates
- Add WindowsExplorerSettings
- Add …

Add and improve multiple artifact definitions

---

data/windows.yaml

Adjusted typo of CurrentControlSet

---

data/macos.yaml

This will allow collection of file system events from the /.fseventsd/ folder on Mac OS X devices.
http://nicoleibrahim.com/apple-fsevents-forensics/

Add FSEvents artifact for macos

---

data/windows.yaml

GRR extended its knowledgebase to support these environment variables, so the interrogation flow needs attached artifacts to fill them.

Add more artifacts for standard Windows variables.

---

data/macos.yaml

Adds an artifact definition for Mojave's Transparency, Consent, and Control framework logs.
References:
- https://blog.fleetsmith.com/tcc-a-quick-primer/
- https://carlashley.com/2018/09/06/reading-tcc-logs-in-macos/

Add MacOSTCC

---

data/webbrowser.yaml

Add alternate path for chrome-remote-desktop Chrome profile location (%%users.homedir%%/.config/chrome-remote-desktop/chrome-config/google-chrome/)

Add additional path for chrome-remote-desktop

---

data/cloud_services.yaml

Examples:
- C:/Users/<user>/AppData/Local/Google/Drive/user_default/sync_log.log
- C:/Users/<user>/AppData/Local/Google/Drive/user_default/sync_log.log.1
- C:/Users/<user>/AppData/Local/Google/Drive/user_default/sync_log.log.2

Update GoogleDrive's Sync log artifact

---

data/windows.yaml

On new versions of windows,  qmgr*.dat no longer exists.
Here is what I have on my computer running Windows 10 21H1 :
C:\ProgramData\Microsoft\Network\Downloader>dir /B
edb.chk
edb.log
edb00007.log
edbres00001.jrs
edbres00002.jrs
edbtmp.log
qmgr.db
qmgr.jfm

WindowsBITSQueueManagerDatabases: collect recent database too

---

data/windows.yaml

`WindowsEventLogs` artifact only pulls certain type of eventlogs, ex:
WindowsEventLogApplication
WindowsEventLogSecurity
WindowsEventLogSystem
changing it to include other eventlog files (ex: powershell), it will collect any of the .evtx or .evt files on the host in any of the default folders in different win versions, please see: https://artifacts-kb.readthedocs.io/en/latest/sources/windows/EventLog.html

Changed WindowsEventLogs definition to FILE source

---

artifacts/definitions.py
data/kubernetes.yaml

Heyho together! 
I am currently finalizing my master thesis about `Kubernetes Forensics` where one objection is the identification and description of forensic artifacts related to Kubernetes.
To identify them, I have used a method of automated differential analysis between two states, mainly working with `Pod` resources. That allows to trace changes on a nodes file system level so that characteristic file changes can be identified and analyzed. 
To bring my results into a usable and understandable format I have chosen to follow your formatting guidelines so that the results can get contributed to the repo. 
I hope that I understood the guidelines correctly and did not mess up completely ... :D 
To mark the purpose/ type of a placeholder in paths i have decided to use the following style: …

Adding Kubernetes artifacts

---

data/live_response.yaml
data/triage.yaml
data/windows.yaml

A templated set of Artifact Groups that captures Windows artifacts and can be extended for Mac and Linux later. The purpose is to use those groups for Triage / Live Response analysis of systems.

Live Response grouping of artifact definitions

---

tools/validator.py

Common typo found: "seperator" -- should it be "separator"?

Corrected typo

---

data/instant_messaging.yaml
data/linux.yaml

Additional Linux artifacts:
- Debian APT history term
- Systemd journal logs
- Gnome tracker files (databases)

Update Linux artifacts.

---

data/windows.yaml

Used to store Active Directory user credentials, among other things

Add artifact for NTDS.dit

---

data/linux.yaml

Adds new Linux artifact definitions:
- `udev` rules [local persistence]
- `at` jobs temporary outputs [local persistence]
- Kerberos configuration file (with Kerberos realm(s) & `KDC`) default location [system info]
- ifupdown scripts [local persistence]
- nano history file [files access]

Added Linux artifact definitions

---

data/shell.yaml

'supported_os' field added for path '%%users.homedir%%/.bash_history' under BashShellHistoryFile

Added supported_os to source in BashShellHistoryFile definition

---

data/installed_module_paths.yaml

Adds new artifacts which collect the paths of commonly used third-party package managers.
Python packages, NPM packages, Flatpak apps (linux only). Visual Studio Code extensions (linux, windows, mac).
Useful for gathering a quick snapshot of the name and number of packages without the contents.

Add artifact to find package manager module paths

---

data/ics.yaml

This PR creates new ics.yaml file and adds definition for Siemens WinCC software logs.

Add definition for Siemens WinCC logs

---

data/macos.yaml

Adding `/var/log/DiagnosticMessages/*.asl` to `MacOSAppleSystemLogFile`. Fixes #548

Updating ASL file locations.

---

data/linux.yaml

Notably on Ubuntu, the syslog file is /var/log/syslog, not /var/log/syslog.log

Modified syslog glob to match more files

---

data/webbrowser.yaml

Updating SafariCache for more modern Cache location:
https://echoone.com/filejuicer/formats/cache#:~:text=Where%20to%20find%20the%20Cache,Library%2FCaches%2F%20)%20folder.

adding a definition for modern macOS

---

artifacts/data/webservers.yaml

This is the default logging path for IIS on my Windows Server 2019. If it's not a typo, this should be added as a separate line.

adding W3SVC to filepath

---

artifacts/data/linux.yaml

Expand the wildcards for some of the linux log files to catch rotated logs with various rotated names.

Expand linux logs coverage

---

artifacts/data/containerd.yaml
artifacts/data/docker.yaml

Adding containerd and Docker root directory. This can be used by `image_export.py` to export the artifacts.

Added containerd and Docker root directory path

---

artifacts/data/macos.yaml

Older Mac versions store crontabs at /var/cron/tabs/* and /var/at/tabs/*  when a user runs crontab -e.

Add extra paths for MacOS Crontab

---

artifacts/data/shell.yaml

Some Darwin systems use Fish shell. This PR adds support for the OS.

Added Darwin as supported_os for Fish History
